name: Deploy to Portainer

env:
  STACKNAME: nextcloud
  IMAGENAME: nextcloud

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from latest release
        id: version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=$(gh release view --latest --json tagName --jq '.tagName')
          VERSION=${TAG#v}
          echo "full_version=$VERSION" >> $GITHUB_OUTPUT
          echo "Found Version: $VERSION"

      - name: Deploy stack
        uses: robin-moser/portainer-stack-deploy@v2
        with:
          portainer-host: ${{ secrets.PORTAINER_HOST }}
          token: ${{ secrets.PORTAINER_TOKEN }}
          swarm-id: ${{ secrets.PORTAINER_SWARM_ID }}
          stack-name: ${{ env.STACKNAME }}
          tag-replacements: |
            ${{ secrets.REGISTRY_URL }}/${{ env.IMAGENAME }}:${{ steps.version.outputs.full_version }}
